name: ui-deploy

defaults:
  run:
    working-directory: tcw-ui

on:
  push:
    branches:
      - main
      - master

env:
  ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
  ALGOLIA_DATA_API_KEY: ${{ secrets.ALGOLIA_DATA_API_KEY }}
  ALGOLIA_SEARCH_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
  ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}
  JANDI_HOOK: ${{ secrets.JANDI_HOOK }}
  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
  SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
  SENTRY_ORG: ${{secrets.SENTRY_ORG}}
  SENTRY_PROJECT: ${{secrets.SENTRY_PROJECT}}

jobs:
  cd:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16]

    steps:
      - name: Checkout 🛎
        uses: actions/checkout@master

      - name: Setup node env 🏗
        uses: actions/setup-node@v2.4.1
        with:
          node-version: ${{ matrix.node }}
          check-latest: true

      - name: Cache node_modules 📦
        uses: actions/cache@v2.1.6
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies 👨🏻‍💻
        run: npm ci --prefer-offline --no-audit

      - name: Prepare env
        run: touch .env
 
      - name: Build UI
        run: npm run generate:gh
      
      - name: Sync search index
        run: node ./tools/sync-search-index.js

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.8.0
        with:
          DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          PUBLISH_BRANCH: gh-pages
          PUBLISH_DIR: ./tcw-ui/dist
